### ISSUE TITLE
Change is not triggered on the input field

### ISSUE THREAD

**Issue by dotmartin** [claviska/jquery-minicolors#191] opened 2016-02-02 10:18 UTC
In our setup we need to listen to the change event on the input field. This is due to how the DOM is loaded in our backbone project. 

Is there a way to force trigger a change event on the actual input field when the color changes by user input via the colorpicker? 

Thanks in advance!

**Comment by claviska** [comment] 2016-02-02 16:14
The change event is triggered on the input as you're expecting. If this isn't happening, it's probably a bug because it should be [per this line](https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.js#L795).

I can't replicate it, so a minimal example or a quick step-by-step would be helpful.

**Comment by darjiyogen** [comment] 2016-03-10 13:34
@claviska : great tool, love it. but one question,

Why text selection in IE is prevented in code?

// Prevent text selection in IE
input.parent().find('.minicolors-panel').on('selectstart', function () { return false; }).end();

Thanks in advance

**Comment by claviska** [comment] 2016-03-10 16:46
This prevents certain versions of IE from drawing a highlight over the control when you drag. I believe IE9 and below, but it may affect newer ones too.

**Comment by DB1990** [comment] 2016-06-12 08:22
@claviska I have this problem. The method does not change srabatyvyet when you enter in the input field values using the keypad.
Now change the method works when you drag the slider. What can I do to solve this problem quickly?

**Comment by claviska** [comment] 2016-06-13 13:17
The change event fires when you use the keyboard, but not on every keystroke. Change will only fire when a valid hex color has been entered (e.g. shorthand or full hex color). This is by design, otherwise it would fire with an invalid color code.

You'll also notice that the color code will revert if you tab out of the field after entering an invalid color. This is also the correct behavior.

**Comment by claviska** [comment] 2016-06-13 13:17
This issue is rather old and since we don't have similar reports or a minimal test case I'm closing it.

**Closed by claviska** 2016-06-13 13:17 UTC
Labels: Bug
